spring:
  datasource:
    url: jdbc:mysql:///shop1903
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.191.191
    virtual-host: /
  redis:
    host: 192.168.191.191
dubbo:
  registry:
    address: zookeeper://192.168.191.191:2181
  protocol:
    port: -1
  application:
    name: goods_service
  consumer:
    check: false
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml