dubbo:
  application:
    name: search_service
  registry:
    address: zookeeper://192.168.191.191:2181
  protocol:
    port: -1
  consumer:
    check: false
spring:
  data:
    solr:
      host: http://192.168.191.191:8983/solr/mycollection
  rabbitmq:
    host: 192.168.191.191
    virtual-host: /