spring:
  datasource:
    url: jdbc:mysql:///shop1903
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
  redis:
    host: 192.168.191.191
dubbo:
  application:
    name: user_service
  registry:
    address: zookeeper://192.168.191.191:2181
  protocol:
    port: -1
  consumer:
    check: false
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml