server:
  port: 8086
spring:
  redis:
    host: 192.168.191.191
dubbo:
  application:
    name: order_web
  registry:
    address: zookeeper://192.168.191.191:2181
  consumer:
    check: false
    timeout: 10000
